site_name: BobTelegramTools
docs_dir: docs_src/
site_dir: docs/
nav:
    - Home: index.md
    - Tutorials: 
        - Create a Telegram bot: bot_father.md
        - Use a bot : bot_ex.md
        - Keras Callback: keras_ex.md
        - Telegram ProgressBar: utilities_ex.md
    - Modules: 
        - Bot: bot.md
        - Keras: keras.md
        - Utils: utilities.md
theme:
  name: 'material'
  logo: 
      icon: 'settings_ethernet'
  feature:
      tabs: false
  palette:
      primary: 'light blue'
      accent: 'light blue'
markdown_extensions:
  - admonition